<div class="footer_button has_offer_prop inner_content js_offers__375">
								<div class="sku_props">
																														<div class="bx_catalog_item_scu wrapper_sku" id="bx_3966226736_375_sku_tree" data-site_id="s1" data-id="375" data-offer_id="367" data-propertyid="205" data-offer_iblockid="21">
																								
														<div class="item_wrapper"><div class="bx_item_detail_size" style="" id="bx_3966226736_375_prop_300_cont" data-display_type="LI" data-id="300"><span class="show_class bx_item_section_name"><span>Модель</span></span><div class="bx_size_scroller_container"><div class="bx_size"><ul id="bx_3966226736_375_prop_300_list" class="list_values_wrapper"><li class="item" data-treevalue="300_219" data-showtype="li" data-onevalue="219" title="Модель: CV 1-2"><i></i><span class="cnt">CV 1-2</span></li><li class="item active" data-treevalue="300_220" data-showtype="li" data-onevalue="220" title="Модель: CV 1-3"><i></i><span class="cnt">CV 1-3</span></li><li class="item" data-treevalue="300_353" data-showtype="li" data-onevalue="353" title="Модель: CV 1-4"><i></i><span class="cnt">CV 1-4</span></li><li class="item" data-treevalue="300_221" data-showtype="li" data-onevalue="221" title="Модель: CV 1-5"><i></i><span class="cnt">CV 1-5</span></li><li class="item" data-treevalue="300_354" data-showtype="li" data-onevalue="354" title="Модель: CV 1-6"><i></i><span class="cnt">CV 1-6</span></li><li class="item" data-treevalue="300_222" data-showtype="li" data-onevalue="222" title="Модель: CV 1-7"><i></i><span class="cnt">CV 1-7</span></li><li class="item" data-treevalue="300_355" data-showtype="li" data-onevalue="355" title="Модель: CV 1-8"><i></i><span class="cnt">CV 1-8</span></li><li class="item" data-treevalue="300_223" data-showtype="li" data-onevalue="223" title="Модель: CV 1-9"><i></i><span class="cnt">CV 1-9</span></li><li class="item" data-treevalue="300_356" data-showtype="li" data-onevalue="356" title="Модель: CV 1-10"><i></i><span class="cnt">CV 1-10</span></li><li class="item" data-treevalue="300_357" data-showtype="li" data-onevalue="357" title="Модель: CV 1-11"><i></i><span class="cnt">CV 1-11</span></li></ul></div></div></div></div>											</div>
																																						</div>
																											<div class="offer_buy_block">
																						<div class="counter_wrapp">
																									<div class="counter_block" data-item="368"><span class="minus">-</span><input type="text" class="text" name="quantity" value="1"><span class="plus">+</span></div>
																								<div id="bx_3966226736_375_basket_actions" class="button_block"><span data-value="32038" data-currency="RUB" data-rid="" class="small read_more1 to-cart btn btn-default transition_bg animate-load" data-props="" data-item="368" data-float_ratio="" data-ratio="1" data-bakset_div="bx_basket_div_368" data-part_props="Y" data-add_props="Y" data-empty_props="" data-offers="Y" data-iblockid="18" data-quantity="1"><i></i><span>В корзину</span></span><a rel="nofollow" href="/basket/" class="small read_more1 in-cart btn btn-default transition_bg" data-props="" data-item="368" style="display:none;"><i></i><span>В корзине</span></a><span class="hidden" data-js-item-name="CV 1-3"></span></div>
											</div>
										</div>
																												<div class="counter_wrapp ce_cmp_visible">
										<div id="bx_3966226736_375_basket_actions_cmp" class="button_block wide">
											<a class="btn btn-default basket read_more" rel="nofollow" data-item="375" href="/catalog/vodosnabzhenie_/nasosy_dlya_zhilykh_i_administrativnykh_zdaniy/vertikalnye_mnogostupenchatye_nasosy/375/?oid=368">Подробнее</a>
										</div>
									</div>
															</div>